### ISSUE TITLE
Number of meshes in make_auxiliary_dat_file.py is fixed to 7

### ISSUE THREAD

**Issue by kaftanski** [fkong7/MeshDeformNet#1]
The Code for [data/make_auxiliary_dat_file.py](https://github.com/fkong7/MeshDeformNet/blob/main/data/make_auxiliary_dat_file.py) does not respect the command line option --num_mesh, because in line 144, the variable num_mesh is fixed to 7. 

This leads to size mismatches during training. When trying to use train_gcn.py on 4 meshes I got the error:
```
ValueError: Dimension size must be evenly divisible by 4 but is 80458
    Number of ways to split should evenly divide the split dimension for 'position/split' (op: 'Split') with input shapes: [], [80458,3] and with computed input tensors: input[0] = <0>.
```
caused by 
```
File "src/model.py", line 46, in build_keras
    mesh_coords_p = Position(mesh_coords, self.feed_dict['mesh_scale'],self.feed_dict['mesh_center'])(image_inputs)
```

**Comment by fkong7** [comment]
Yes, thanks for bringing this up. Please remove line 144 from data/make_auxiliary_dat_file.py and use the desired number of meshes for your application.

**Comment by kaftanski** [comment]
I will do that. Thank you for the quick reply and for your work!
