### ISSUE TITLE
Shape error

### ISSUE THREAD

**Issue by MHD-s** [fkong7/MeshDeformNet#10]
Hello,

Can you please give more details about the `prediction_gcn.py` as i'm having 2 types of shape errors:

- The first one is a cancatenation errors that appears when i use images with the depth value not divisible by 32. (ex. 512 x 512 x 130)

This one occurs when building the decoder part of the Unet.

- The second is a reshape error, where it is trying to reshape a (huge) negative value to a 2 dimensional array.

This happens in the GraphConv function of the decoder part of the gcn.

Here's the script that i used:

```
python prediction_gcn.py \
--image ../
--mesh_dat data/template/data_aux.dat 
--mesh_txt data/template/mesh_info_ct.txt data/template/mesh_info_mr.txt 
--attr input  
--mesh_tmplt  data/template/init3.vtk 
--model weights/weights_gcn.hdf5 
--output ../output 
--modality ct mr 
--seg_id 1 2 3 4 5 6 7 
--size 512 512 128 
--mode test
```

The input image of this example is "mr_test_2007_image.nii.gz" from the MM-WHS 2017 Dataset.

Thank you for your answer !

**Comment by fkong7** [comment]
Please use 128 128 128 as your size - the script will resample your image data to that specified size.

**Comment by MHD-s** [comment]
When using 128 128 128 i get the error below :

![Nan value](https://user-images.githubusercontent.com/74880180/201644104-04b228ca-0931-4360-afeb-558caf038b0b.PNG)

**Comment by MHD-s** [comment]
The problem was the input folder that has to be named `mrinput` or `ctinput` according to the type of the image.
Once the forlder is renamed, the prediction is done correctly.
Thank you !
