### ISSUE TITLE
mesh visualization

### ISSUE THREAD

**Issue by ZimengTan** [fkong7/MeshDeformNet#15]
Hi, Could you please tell me what software or codes (or python library) was used to visualize the meshes in your papers (MeshDeformNet and HeartDeformNets)? They look very exquisite. Thanks a lot!

**Comment by fkong7** [comment]
Hi - I was using Paraview. 

Thanks!

**Comment by ZimengTan** [comment]
Thank you for the quick reply and for your work!!!
