### ISSUE TITLE
No module named 'prediction'

### ISSUE THREAD

**Issue by huilinyang** [fkong7/MeshDeformNet#4]
Hello, I tried to do a prediction with validation, and an error occurred.

> Traceback (most recent call last):
>   File "prediction_gcn.py", line 331, in <module>
>      score_list.append(predict.evaluate_dice())
>   File "prediction_gcn.py", line 148, in evaluate_dice 
>      from prediction import dice_score
> ModuleNotFoundError: No module named 'prediction'

I checked all parts of the project and didn't find the module 'prediction', could you please make it clear? Thanks a lot!

**Comment by fkong7** [comment]
Hello, 

I added the function back in utils.py in the latest commit.

Thanks and please reopen if you have any further issues.
