### ISSUE TITLE
Scale range for data augmentation?

### ISSUE THREAD

**Issue by huilinyang** [fkong7/MeshDeformNet#6]
Hello, hope everything goes well.

The paper denotes the scale range is (-5% to 5%), as in the first following picture. However, the 'scale range' in the code is [0.75 to 1.] (as in the second picture). I am a little bit confused about this. Could you please tell me which one you used in training? Thanks!

![image](https://user-images.githubusercontent.com/20769781/198831322-71c2781c-4e83-4bf2-a404-7e3dcd2c6936.png)

![image](https://user-images.githubusercontent.com/20769781/198831549-9d3df42f-1b1c-4adf-a9ac-677b2bdcc704.png)

**Comment by fkong7** [comment]
I probably have tried both, thus the discrepancy. I would go with the code, [0.75, 1]. There shouldn't be much difference in practice since non-linear augmentation is much more important compared with scaling.

**Comment by huilinyang** [comment]
Thank you! I think I will try both.
