### ISSUE TITLE
Training time?

### ISSUE THREAD

**Issue by huilinyang** [fkong7/MeshDeformNet#8]
Hi, Could you please tell me how long the model takes to converge when training? (around 1700+ training data after data augmentation in your case). It's really slow on my server, taking up to 10+ hours to train only one epoch with around 740 data.

**Comment by fkong7** [comment]
It took about 32 hours to converge on a 2080ti GPU. It shouldn't take more than an hour to train one epoch on a GPU.

**Comment by huilinyang** [comment]
It might because I trained on a relative newer GPU with CUDA 11.0 but cudatoolkit 10.0. Could you please upload the dependencies so that I can recompile the .cpp and .cu files with CUDA 11.0? Thank you!

**Comment by fkong7** [comment]
What dependencies do you need from us? The source files have been provided.

**Comment by huilinyang** [comment]
I tried to train on a relative older GPU with tensorflow-gpu 1.15.0, cudatoolkit 10.0.130 and cudnn 7.6.0 installed, and it works with less than 1 hour to train an epoch. Thank you so much.
